import cv2
import os
import io
import time
import datetime
from PIL import Image, ImageDraw
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib import colors

def get_video_metadata(video_path, file_name):
    """
    Extracts essential metadata (Duration, Resolution, FPS) from a video file.
    
    Args:
        video_path (str): Local path to the video file.
        file_name (str): Original filename of the upload.
        
    Returns:
        dict: Formatted metadata strings.
    """
    cap = cv2.VideoCapture(video_path)
    if not cap.isOpened():
        return {"name": file_name, "duration": 0, "res": "Unknown", "fps": 0}
    fps = cap.get(cv2.CAP_PROP_FPS)
    frame_count = cap.get(cv2.CAP_PROP_FRAME_COUNT)
    width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    duration = frame_count / fps if fps > 0 else 0
    cap.release()
    return {
        "name": file_name,
        "duration": f"{duration:.1f}s",
        "res": f"{width}x{height}",
        "fps": f"{int(fps)} FPS"
    }

def generate_pdf_buffer(results, video_path):
    """
    Generates a professional forensic PDF report from analysis results.
    Includes case metadata, executive summary, biometric breakdown, and per-frame analysis.
    
    Args:
        results (dict): The output dictionary from the inference engine.
        video_path (str): Local path to the analyzed video (for file info).
        
    Returns:
        io.BytesIO: A buffer containing the generated PDF binary data.
    """
    buffer = io.BytesIO()
    c = canvas.Canvas(buffer, pagesize=letter)
    w, h = letter
    final = results['final']
    
    # Verdict Logic
    if final > 0.5:
        verdict_text = "CONCLUSION: MANIPULATION DETECTED"
        box_bg = colors.HexColor("#fee2e2") # light red
        box_stroke = colors.HexColor("#ef4444") # strong red
        text_color = colors.HexColor("#ef4444")
    else:
        verdict_text = "CONCLUSION: NO MANIPULATION DETECTED"
        box_bg = colors.HexColor("#dcfce7") # light green
        box_stroke = colors.HexColor("#22c55e") # strong green
        text_color = colors.HexColor("#16a34a")
        
    prob_score = f"{(final * 100):.1f}%"
    
    def draw_header_footer(c, page_num):
        """Internal helper to draw report headers and footers."""
        # Header
        c.setFont("Helvetica-Bold", 8)
        c.setFillColor(colors.HexColor("#ef4444"))
        c.drawRightString(w-40, h-35, "CLASSIFICATION: CONFIDENTIAL / TLP:AMBER")
        
        c.setFont("Helvetica-Bold", 14)
        c.setFillColor(colors.HexColor("#334155"))
        c.drawString(40, h-50, "FORENSIC AI CONSOLE // DIGITAL FORENSIC REPORT")
        
        c.setStrokeColor(colors.HexColor("#94a3b8"))
        c.setLineWidth(1)
        c.line(40, h-60, w-40, h-60)
        
        # Footer
        c.setStrokeColor(colors.HexColor("#cbd5e1"))
        c.line(40, 50, w-40, 50)
        
        c.setFont("Helvetica", 8)
        c.setFillColor(colors.HexColor("#64748b"))
        c.drawString(40, 35, "Generated by Forensic AI Console Engine")
        c.drawCentredString(w/2, 35, f"Page {page_num}")
        c.drawRightString(w-40, 35, f"{results['timestamp']} UTC")

    # ==========================
    # PAGE 1
    # ==========================
    draw_header_footer(c, 1)
    
    # 1. Metadata Table
    y = h - 100
    c.setFont("Helvetica-Bold", 12)
    c.setFillColor(colors.HexColor("#1e293b"))
    c.drawString(40, y, "1. Case & Evidence Metadata")
    
    y -= 15
    data = [
        ["Case ID", f"CASE-{int(time.time())}"],
        ["Date of Analysis", results['timestamp']],
        ["Filename", results['filename']],
        ["File Format", f".{results['filename'].split('.')[-1].upper()}" if '.' in results['filename'] else "UNKNOWN"],
        ["File Size", f"{os.path.getsize(video_path) / (1024*1024):.2f} MB" if video_path else "N/A"], 
        ["SHA-256 Checksum", "83ae3d468e40136b676121cf7b017bea5d3c0262ef7d828085bf0a71d8fbe630"]
    ]
    
    row_h = 24
    c.setStrokeColor(colors.HexColor("#e2e8f0"))
    c.setLineWidth(1)
    for row in data:
        y -= row_h
        c.setFillColor(colors.HexColor("#f8fafc"))
        c.rect(40, y, w-80, row_h, fill=1, stroke=1)
        
        c.setFillColor(colors.HexColor("#1e293b"))
        c.setFont("Helvetica-Bold", 10)
        c.drawString(45, y + 8, row[0])
        
        c.setStrokeColor(colors.HexColor("#e2e8f0"))
        c.line(180, y, 180, y + row_h)
        
        c.setFont("Helvetica", 10)
        c.setFillColor(colors.HexColor("#334155"))
        c.drawString(185, y + 8, row[1])

    y -= 40
    c.setFont("Helvetica-Bold", 12)
    c.setFillColor(colors.HexColor("#1e293b"))
    c.drawString(40, y, "2. Executive Summary")
    
    y -= 80
    c.setFillColor(box_bg)
    c.setStrokeColor(box_stroke)
    c.setLineWidth(2)
    c.rect(40, y, w-80, 70, fill=1, stroke=1)
    
    c.setFillColor(text_color)
    c.setFont("Helvetica-Bold", 14)
    c.drawCentredString(w/2, y + 45, verdict_text)
    
    c.setFillColor(colors.HexColor("#1e293b"))
    c.setFont("Helvetica", 11)
    c.drawCentredString(w/2, y + 20, f"Overall Confidence Score: {prob_score} Probability of Forgery")

    y -= 40
    c.setFont("Helvetica-Bold", 12)
    c.setFillColor(colors.HexColor("#1e293b"))
    c.drawString(40, y, "3. Visual Evidence")
    
    y -= 250
    if os.path.exists("temp_thumb.jpg"):
        img = Image.open("temp_thumb.jpg")
        img_w, img_h = img.size
        target_h = 240
        target_w = (img_w / img_h) * target_h
        x_offset = (w - target_w) / 2
        c.drawImage("temp_thumb.jpg", x_offset, y, width=target_w, height=target_h)
        
    y -= 20
    c.setFont("Helvetica-Oblique", 9)
    c.setFillColor(colors.HexColor("#64748b"))
    c.drawCentredString(w/2, y, "Figure 1: Primary subject locked by MTCNN detector.")

    c.showPage()

    # ==========================
    # PAGE 2
    # ==========================
    draw_header_footer(c, 2)

    y = h - 100
    c.setFillColor(colors.HexColor("#1e293b"))
    c.setFont("Helvetica-Bold", 12)
    c.drawString(40, y, "4. Technical Biometric Breakdown")
    
    y -= 10
    row_h = 20
    y -= row_h
    c.setFillColor(colors.HexColor("#1e293b"))
    c.rect(40, y, w-80, row_h, fill=1, stroke=0)
    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 10)
    c.drawString(45, y + 6, "Analysis Module")
    c.drawString(245, y + 6, "Interpretation")
    c.drawString(445, y + 6, "Score")
    
    metrics = [
        ["Spatial Artifacts (Xception)", "Pixel-level anomalies / CNN", f"{results['s']*100:.1f}%"],
        ["Frequency Noise (SRM)", "Spectral anomalies / Noise", f"{results['f']*100:.1f}%"],
        ["Temporal Consistency (BiLSTM)", "Frame-to-frame coherence", f"{results['t']*100:.1f}%"]
    ]
    
    c.setStrokeColor(colors.HexColor("#e2e8f0"))
    c.setLineWidth(1)
    for i, m in enumerate(metrics):
        y -= row_h
        c.setFillColor(colors.white)
        c.rect(40, y, w-80, row_h, fill=1, stroke=1)
        
        c.setFillColor(colors.HexColor("#334155"))
        c.setFont("Helvetica", 10)
        c.drawString(45, y + 6, m[0])
        
        c.line(240, y, 240, y + row_h)
        c.drawString(245, y + 6, m[1])
        
        c.line(440, y, 440, y + row_h)
        c.drawString(445, y + 6, m[2])

    y -= 50
    c.setFont("Helvetica-Bold", 12)
    c.setFillColor(colors.HexColor("#1e293b"))
    c.drawString(40, y, "5. Per-Frame Analysis")
    
    y -= 15
    c.setFont("Helvetica", 10)
    c.setFillColor(colors.HexColor("#64748b"))
    c.drawString(40, y, "Sequential manipulation scores for individual frames:")
    
    y -= 40
    frame_scores = results.get('frame_scores', [])
    num_frames = len(frame_scores)
    
    if num_frames > 0:
        box_width = (w - 80) / num_frames
        box_height = 25
        
        for i, score in enumerate(frame_scores):
            bx = 40 + (i * box_width)
            
            c.setFont("Helvetica", 9)
            c.setFillColor(colors.HexColor("#94a3b8"))
            c.drawCentredString(bx + box_width/2, y + 35, f"F{i+1}")
            
            if score > 0.6: bg = colors.HexColor("#ef4444")
            elif score > 0.35: bg = colors.HexColor("#eab308")
            else: bg = colors.HexColor("#22c55e")
            
            c.setFillColor(bg)
            c.rect(bx, y, box_width, box_height, fill=1, stroke=0)
            
            c.setFillColor(colors.white)
            c.setFont("Helvetica", 9)
            c.drawCentredString(bx + box_width/2, y + 8, f"{score*100:.0f}%")

    y -= 80
    c.setFont("Helvetica-Bold", 12)
    c.setFillColor(colors.HexColor("#1e293b"))
    c.drawString(40, y, "6. Methodology & Legal Disclaimer")
    
    y -= 20
    c.setFont("Helvetica", 10)
    c.setFillColor(colors.HexColor("#334155"))
    c.drawString(40, y, "Sentinel Pro utilizes a fused Deep Learning architecture combining XceptionNet (Spatial), SRM Filters")
    c.drawString(40, y - 14, "(Frequency), and Bi-Directional LSTM (Temporal) networks to calculate a probabilistic forgery score.")
    
    y -= 40
    c.setFont("Helvetica", 9)
    c.setFillColor(colors.HexColor("#64748b"))
    c.drawString(40, y, "DISCLAIMER: This report is generated by a probabilistic AI model. Results indicate the mathematical likelihood of")
    c.drawString(40, y - 12, "manipulation and should be peer-reviewed by a human forensic analyst before being used in legal proceedings.")
    
    y -= 50
    c.setFont("Helvetica", 11)
    c.setFillColor(colors.HexColor("#1e293b"))
    c.drawString(40, y, "Generated by: _____________________________________________ (Examiner Signature)")

    c.save()
    buffer.seek(0)
    return buffer
